# Generated by Django 3.2.6 on 2021-08-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robitcontrol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robit',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='robit',
            name='channel_name',
            field=models.CharField(default=None, max_length=64, null=True, unique=True),
        ),
    ]
