# Generated by Django 3.2.6 on 2021-08-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robitcontrol', '0002_auto_20210811_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robit',
            name='channel_name',
            field=models.CharField(default=None, max_length=128, null=True, unique=True),
        ),
    ]
