# Generated by Django 3.2.6 on 2021-08-18 17:29

from django.db import migrations, models
import robitcontrol.models


class Migration(migrations.Migration):

    dependencies = [
        ('robitcontrol', '0003_alter_robit_channel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebRTCBrowser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('token', models.CharField(db_index=True, default=robitcontrol.models.random_token, max_length=16, unique=True)),
                ('key', models.CharField(default=robitcontrol.models.random_key, max_length=64)),
            ],
        ),
    ]
